### PR TITLE
WIP discontinuity discrepancy in PAGE

### PR DESCRIPTION
**Pull request by ckingdon95**
Work in progress--

This PR will check for SCC's computed during PAGE's monte carlo simulation where discontinuity damages are triggered in a different timestep in the marginal run of the model than in the base run, and remove these values from the computed SCC averages

### CODE REVIEW

**Comment by bryanparthum** [comment]
Cora/David, the PAGE discontinuity flag is operating as expected thanks to @tammyt123 's efforts and has merged that work with this branch. Running validation and comparison to IWG CH4 and N2O estimates now, but the HFC discontinuities were spot on (0.02%-0.05% of runs flagged). 

We should also talk about if merging the HFC work makes sense in this repo? Everything is up to date on [our fork](https://github.com/bryanparthum/MimiIWG.jl).

**Comment by lrennels** [comment]
@bryanparthum just saw this and will look into it next week!

**Comment by lrennels** [comment]
@bryanparthum and @tammyt123  am I interpreting your comment correctly that this branch now contains everything needed to satisfy the original goal of the PR? It looks like @tammyt123 and you implemented the nuts and bolts and @ckingdon95 has added a `drop_discontinuities` option flag?  If so I can merge this and close the PR to keep things clean, and then if we're interested in adding the HFC work we can open a separate PR for that?

**Comment by bryanparthum** [comment]
That is correct. I haven't tested the `discontinuities_drop` option that Cora added. But the `discontinuities_mismatch` folder that is created in the output file works great (and we post-process the discontinuities). As far as checking, you're correct that it would be a little difficult to do. The basic idea is that the discontinuities is a simple pass/fail of several conditions, so it is _somewhat_ deterministic in that sense. I'll have to think a little more about how it could fail on each iteration of the simulation.

**Comment by lrennels** [comment]
Great, for now I can just add it to the API to make sure it runs (I did that above already) and then we can add a different Issue to add testing. We aren’t testing the non deterministic at all in this package anyways as far as I can tell so that’s probably a good idea on a bigger scale.

**Comment by lrennels** [comment]
I can add it as another part of PR #7

**Comment by lrennels** [comment]
@bryanparthum I am revisiting this repository to add Ramsey discounting and equity weighting options for some work I am doing, which we may or may not merge depending on how confusing it would be for current users (we can discuss that when the time comes).  In this work I was adopting the drop discontinuities stuff, and noticed that their had been a different spot allocated for each discount rate to count the discontinuities ... but am I right in saying that there's no real reason this would differ between discount rates?  

Looking at the code for MimiIWG and PAGE2009, it cannot see how they could differ, given the Discontinuity component does not pull from the Equity Weighting component ... which is I think the only way it could be drawing from discounted values.

**I'm not an expert on PAGE, and could be wrong, so don't waste your time digging too deep I can do that if I seem off!  Just wondering if in your work you tend to expect the results to ever differ between discount rates or if those columns are always the same.**

**Comment by bryanparthum** [comment]
Hey Lisa! You are correct, the discount rate won't make a difference in the occurrence of a discontinuity indicator as it is only function of temperature anomalies and the probability of them occuring. If there is a spot in the payload for each discontinuity/discount rate combination, it might just have something to do with the order that they are stored in the code.


___________________
Bryan Parthum, PhD
Economist, U.S. EPA Office of Policy
National Center for Environmental Economics
202.564.1045
he/him

**Pull request merged**
